env:
  browser: true
  commonjs: true
  es2020: true
extends:
  - google
  - plugin:prettier/recommended
  - prettier
plugins:
  - prettier
parserOptions:
  ecmaVersion: 11
rules:
  prettier/prettier: 'error'
